### PR TITLE
"Full Sized" TSA Master Keys

### PR DESCRIPTION
**Pull request by johnnyxmas**
Added “Full Size” keys for both long and stubby. Ratio is 157.142% on
X/Y and 64% on Z. Tested only on 007 lock.

### CODE REVIEW

**Comment by MS3FGX** [comment]
On my PrintrBot Metal, the 007 key works with some slight trimming (but that could be due to PLA swell in my particular environment), but the 002 key isn't even close. It doesn't line up with the keyway at all. Though the original one doesn't either, admittedly.

Personally I think that with the number of keys and all the different factors involved, applying changes to all of them at once is not the safest approach. I think we should tackle one key at a time, and merge them into the main repo as we get positive feedback from at least 2 or 3 users (to try and rule out issues with individual setups).

I also think all the directories, while maybe more orderly, is overkill. We should find one size, and stick with it, rather than have different directories with different scales. It is only going to confuse people.

So my vote would be not to merge this request in, but instead make a new pull request for **just** the larger scale 007 to replace the existing one (again, assuming we get a majority vote that it's working for people).

**Comment by johnnyxmas** [comment]
Makes sense, given that these were made visually. I'm sending test sets out to people with many of the locks, and asking them for the same measurements I used for correcting 007. 

I'll keep all my stuff on my end and submit pull requests for keys as soon as I can individually modify & confirm them (others should do the same). Needing a slight trim to account for environmental factors is fine, as that's just inherent in 3D printing and can be accounted for during slicing. I'd at least like to have them "very close" in the files.

**Comment by Xyl2k** [comment]
so, we don't merge it ? or only the TSA007 and we asks users for feedbacks ? (i think it's the best option)

**Comment by MS3FGX** [comment]
TSA007 seems like an improvement, so that should probably be merged in. But the others are untested, and I don't think they should be merged until we can get some more users to confirm what works for them.

I would be very interested to see if we can find somebody who printed out one of the original TSA007s and have them print the new larger version. If the original one worked for them, does that mean this one will be too large?

**Comment by johnnyxmas** [comment]
I'm going to merge the 007. I just printed 2 more sets, and they're working great on my end.

**Comment by MS3FGX** [comment]
There should still be some form of consensus. At the absolute least, we should try and get one of the people who successfully printed the original files to print/test one of the enlarged ones.

What is the point of updating the files so they work for some people, if at the same time it prevents them from working with the existing users?

**Comment by Xyl2k** [comment]
for the moment i can't test as i don't have TSA locks, but i should get some from ebay.
007, 002, 003 and 005
tzsg4cvh

**Comment by johnnyxmas** [comment]
I have 5 sets going out USPS tomorrow to known locksport enthusiasts who claim to have access to several TSA locks. Also, my local Toool chapter is seeing what they can get together.

**Comment by johnnyxmas** [comment]
Closing this pull request in order to do individual files.

**Pull request closed without merging**
